version: '2'
services:
  app:
    build: .
    # command: run dev
    env_file: .env
    image: demo
    network_mode: bridge
    ports:
    - ${PORT}:${PORT}
    # volumes:
    # - ./:/code
    # - /code/node_modules
    depends_on:
      - mysql
    links:
      - mysql
  mysql:
    network_mode: bridge
    image: mysql:5.7
    # command: --default-authentication-plugin=mysql_native_password
    env_file: .env
    ports:
    - 3306:3306
    expose:
    - 3306
    
    # environment:
    #   MYSQL_ROOT_PASSWORD: example
    