module.exports.data = [
    {
        "marketDashboardQueryRes": [
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Axio",
                "squareFeet": 975,
                "surveyDate": "2018-02-01",
                "occupancyRate": 41.8,
                "lastUpdatedDate": "2018-03-12T12:08:50.957",
                "numberUnitsBeds": 262,
                "propertyGoldenId": "PMST498969",
                "marketRentUnitBedAmount": 1725.37,
                "rentPerSquareFootAmount": 1.49,
                "effectiveRentUnitBedAmount": 1437.85,
                "marketStandardAdjustedRentUnitAmount": null
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Axio",
                "squareFeet": 975,
                "surveyDate": "2018-03-01",
                "occupancyRate": 49,
                "lastUpdatedDate": "2018-04-17T13:29:37.730",
                "numberUnitsBeds": 262,
                "propertyGoldenId": "PMST498969",
                "marketRentUnitBedAmount": 1763.98,
                "rentPerSquareFootAmount": 1.52,
                "effectiveRentUnitBedAmount": 1470.05,
                "marketStandardAdjustedRentUnitAmount": null
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Axio",
                "squareFeet": 975,
                "surveyDate": "2018-04-01",
                "occupancyRate": 32.8,
                "lastUpdatedDate": "2018-05-11T08:18:12.217",
                "numberUnitsBeds": 262,
                "propertyGoldenId": "PMST498969",
                "marketRentUnitBedAmount": 1759.22,
                "rentPerSquareFootAmount": 1.45,
                "effectiveRentUnitBedAmount": 1400.31,
                "marketStandardAdjustedRentUnitAmount": null
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Axio",
                "squareFeet": 975,
                "surveyDate": "2018-05-01",
                "occupancyRate": 50,
                "lastUpdatedDate": "2018-06-11T16:48:13.907",
                "numberUnitsBeds": 262,
                "propertyGoldenId": "PMST498969",
                "marketRentUnitBedAmount": 1697.45,
                "rentPerSquareFootAmount": 1.35,
                "effectiveRentUnitBedAmount": 1296.65,
                "marketStandardAdjustedRentUnitAmount": null
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Axio",
                "squareFeet": 975,
                "surveyDate": "2018-06-01",
                "occupancyRate": 55,
                "lastUpdatedDate": "2018-07-16T19:25:06.963",
                "numberUnitsBeds": 262,
                "propertyGoldenId": "PMST498969",
                "marketRentUnitBedAmount": 1700.25,
                "rentPerSquareFootAmount": 1.47,
                "effectiveRentUnitBedAmount": 1417.07,
                "marketStandardAdjustedRentUnitAmount": null
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Axio",
                "squareFeet": 1074,
                "surveyDate": "2018-07-01",
                "occupancyRate": 77.5,
                "lastUpdatedDate": "2018-09-23T14:57:20.963",
                "numberUnitsBeds": 262,
                "propertyGoldenId": "PMST498969",
                "marketRentUnitBedAmount": 1823.53,
                "rentPerSquareFootAmount": 1.58,
                "effectiveRentUnitBedAmount": 1671.63,
                "marketStandardAdjustedRentUnitAmount": null
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Axio",
                "squareFeet": 1074,
                "surveyDate": "2018-08-01",
                "occupancyRate": 85.5,
                "lastUpdatedDate": "2018-09-30T11:18:43.123",
                "numberUnitsBeds": 262,
                "propertyGoldenId": "PMST498969",
                "marketRentUnitBedAmount": 1822.95,
                "rentPerSquareFootAmount": 1.58,
                "effectiveRentUnitBedAmount": 1671.08,
                "marketStandardAdjustedRentUnitAmount": null
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Axio",
                "squareFeet": 1080,
                "surveyDate": "2018-09-01",
                "occupancyRate": 85.5,
                "lastUpdatedDate": "2018-10-31T19:22:42.037",
                "numberUnitsBeds": 262,
                "propertyGoldenId": "PMST498969",
                "marketRentUnitBedAmount": 1831.51,
                "rentPerSquareFootAmount": 1.58,
                "effectiveRentUnitBedAmount": 1678.94,
                "marketStandardAdjustedRentUnitAmount": null
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Axio",
                "squareFeet": 1080,
                "surveyDate": "2018-10-01",
                "occupancyRate": 87,
                "lastUpdatedDate": "2018-11-30T21:43:03.387",
                "numberUnitsBeds": 262,
                "propertyGoldenId": "PMST498969",
                "marketRentUnitBedAmount": 1830.19,
                "rentPerSquareFootAmount": 1.59,
                "effectiveRentUnitBedAmount": 1697.13,
                "marketStandardAdjustedRentUnitAmount": null
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Axio",
                "squareFeet": 1080,
                "surveyDate": "2018-11-01",
                "occupancyRate": 87,
                "lastUpdatedDate": "2018-12-22T21:45:20.140",
                "numberUnitsBeds": 262,
                "propertyGoldenId": "PMST498969",
                "marketRentUnitBedAmount": 1825.7,
                "rentPerSquareFootAmount": 1.57,
                "effectiveRentUnitBedAmount": 1677.63,
                "marketStandardAdjustedRentUnitAmount": null
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Axio",
                "squareFeet": 1074,
                "surveyDate": "2018-12-01",
                "occupancyRate": 89.3,
                "lastUpdatedDate": "2019-01-22T21:47:42.213",
                "numberUnitsBeds": 262,
                "propertyGoldenId": "PMST498969",
                "marketRentUnitBedAmount": 1817.24,
                "rentPerSquareFootAmount": 1.61,
                "effectiveRentUnitBedAmount": 1708.79,
                "marketStandardAdjustedRentUnitAmount": null
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Axio",
                "squareFeet": 1074,
                "surveyDate": "2019-01-01",
                "occupancyRate": 89.3,
                "lastUpdatedDate": "2019-02-26T22:05:15.610",
                "numberUnitsBeds": 262,
                "propertyGoldenId": "PMST498969",
                "marketRentUnitBedAmount": 1821.08,
                "rentPerSquareFootAmount": 1.63,
                "effectiveRentUnitBedAmount": 1733.78,
                "marketStandardAdjustedRentUnitAmount": null
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Axio",
                "squareFeet": 1074,
                "surveyDate": "2019-02-01",
                "occupancyRate": 92,
                "lastUpdatedDate": "2019-03-21T00:08:23.303",
                "numberUnitsBeds": 262,
                "propertyGoldenId": "PMST498969",
                "marketRentUnitBedAmount": 1817.28,
                "rentPerSquareFootAmount": 1.59,
                "effectiveRentUnitBedAmount": 1684.88,
                "marketStandardAdjustedRentUnitAmount": null
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Axio",
                "squareFeet": 1074,
                "surveyDate": "2019-03-01",
                "occupancyRate": 85.5,
                "lastUpdatedDate": "2019-04-29T18:33:22.887",
                "numberUnitsBeds": 262,
                "propertyGoldenId": "PMST498969",
                "marketRentUnitBedAmount": 1819.92,
                "rentPerSquareFootAmount": 1.56,
                "effectiveRentUnitBedAmount": 1652.16,
                "marketStandardAdjustedRentUnitAmount": null,
                "indexedTimeStamp": "2020-10-01T14:39:47.052Z"
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Axio",
                "squareFeet": 1074,
                "surveyDate": "2019-04-01",
                "occupancyRate": 91.6,
                "lastUpdatedDate": "2019-05-18T22:17:19.877",
                "numberUnitsBeds": 262,
                "propertyGoldenId": "PMST498969",
                "marketRentUnitBedAmount": 1816.27,
                "rentPerSquareFootAmount": 1.58,
                "effectiveRentUnitBedAmount": 1667.82,
                "marketStandardAdjustedRentUnitAmount": null,
                "indexedTimeStamp": "2020-10-01T16:40:55.450Z"
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Axio",
                "squareFeet": 1074,
                "surveyDate": "2019-05-01",
                "occupancyRate": 82.8,
                "lastUpdatedDate": "2019-06-16T08:35:55.187",
                "numberUnitsBeds": 262,
                "propertyGoldenId": "PMST498969",
                "marketRentUnitBedAmount": 1816.18,
                "rentPerSquareFootAmount": 1.58,
                "effectiveRentUnitBedAmount": 1667.77,
                "marketStandardAdjustedRentUnitAmount": null,
                "indexedTimeStamp": "2020-10-01T20:03:13.475Z"
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Axio",
                "squareFeet": 1074,
                "surveyDate": "2019-06-01",
                "occupancyRate": 80.1,
                "lastUpdatedDate": "2019-07-22T03:12:39.557",
                "numberUnitsBeds": 262,
                "propertyGoldenId": "PMST498969",
                "marketRentUnitBedAmount": 1816.18,
                "rentPerSquareFootAmount": 1.58,
                "effectiveRentUnitBedAmount": 1667.77,
                "marketStandardAdjustedRentUnitAmount": null,
                "indexedTimeStamp": "2020-10-01T21:52:18.761Z"
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Axio",
                "squareFeet": 1084,
                "surveyDate": "2019-07-01",
                "occupancyRate": 87.4,
                "lastUpdatedDate": "2019-08-18T10:03:59.870",
                "numberUnitsBeds": 262,
                "propertyGoldenId": "PMST498969",
                "marketRentUnitBedAmount": 1836.77,
                "rentPerSquareFootAmount": 1.58,
                "effectiveRentUnitBedAmount": 1686.12,
                "marketStandardAdjustedRentUnitAmount": null,
                "indexedTimeStamp": "2020-10-02T03:48:42.945Z"
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Axio",
                "squareFeet": 1059,
                "surveyDate": "2019-08-01",
                "occupancyRate": 85.5,
                "lastUpdatedDate": "2019-09-20T00:11:32.157",
                "numberUnitsBeds": 262,
                "propertyGoldenId": "PMST498969",
                "marketRentUnitBedAmount": 1832.87,
                "rentPerSquareFootAmount": 1.59,
                "effectiveRentUnitBedAmount": 1655.6,
                "marketStandardAdjustedRentUnitAmount": null,
                "indexedTimeStamp": "2020-10-02T07:18:40.305Z"
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Axio",
                "squareFeet": 1054,
                "surveyDate": "2019-09-01",
                "occupancyRate": 88.1,
                "lastUpdatedDate": "2019-10-20T16:38:31.663",
                "numberUnitsBeds": 262,
                "propertyGoldenId": "PMST498969",
                "marketRentUnitBedAmount": 1836.32,
                "rentPerSquareFootAmount": 1.6,
                "effectiveRentUnitBedAmount": 1655.77,
                "marketStandardAdjustedRentUnitAmount": null,
                "indexedTimeStamp": "2020-10-02T07:43:06.966Z"
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Axio",
                "squareFeet": 1045,
                "surveyDate": "2019-10-01",
                "occupancyRate": 87.4,
                "lastUpdatedDate": "2019-11-18T20:01:24.467",
                "numberUnitsBeds": 237,
                "propertyGoldenId": "PMST498969",
                "marketRentUnitBedAmount": 1824.9,
                "rentPerSquareFootAmount": 1.61,
                "effectiveRentUnitBedAmount": 1646.67,
                "marketStandardAdjustedRentUnitAmount": null,
                "indexedTimeStamp": "2020-10-02T10:30:09.991Z"
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Axio",
                "squareFeet": 1045,
                "surveyDate": "2019-11-01",
                "occupancyRate": 87.7,
                "lastUpdatedDate": "2019-12-15T21:18:17.100",
                "numberUnitsBeds": 237,
                "propertyGoldenId": "PMST498969",
                "marketRentUnitBedAmount": 1738.24,
                "rentPerSquareFootAmount": 1.6,
                "effectiveRentUnitBedAmount": 1643.98,
                "marketStandardAdjustedRentUnitAmount": null,
                "indexedTimeStamp": "2020-10-02T15:09:13.345Z"
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Axio",
                "squareFeet": 1045,
                "surveyDate": "2019-12-01",
                "occupancyRate": 91.9,
                "lastUpdatedDate": "2020-01-20T07:54:55.960",
                "numberUnitsBeds": 237,
                "propertyGoldenId": "PMST498969",
                "marketRentUnitBedAmount": 1727.4,
                "rentPerSquareFootAmount": 1.59,
                "effectiveRentUnitBedAmount": 1637.84,
                "marketStandardAdjustedRentUnitAmount": null,
                "indexedTimeStamp": "2020-10-02T18:18:08.695Z"
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Axio",
                "squareFeet": 1045,
                "surveyDate": "2020-01-01",
                "occupancyRate": 92.8,
                "lastUpdatedDate": "2020-02-21T11:33:26.900",
                "numberUnitsBeds": 237,
                "propertyGoldenId": "PMST498969",
                "marketRentUnitBedAmount": 1714.82,
                "rentPerSquareFootAmount": 1.59,
                "effectiveRentUnitBedAmount": 1637.87,
                "marketStandardAdjustedRentUnitAmount": null,
                "indexedTimeStamp": "2020-10-03T00:32:49.897Z"
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Axio",
                "squareFeet": 1045,
                "surveyDate": "2020-02-01",
                "occupancyRate": 95.7,
                "lastUpdatedDate": "2020-03-18T00:23:38.213",
                "numberUnitsBeds": 237,
                "propertyGoldenId": "PMST498969",
                "marketRentUnitBedAmount": 1694.85,
                "rentPerSquareFootAmount": 1.59,
                "effectiveRentUnitBedAmount": 1632.38,
                "marketStandardAdjustedRentUnitAmount": null,
                "indexedTimeStamp": "2020-10-03T05:00:46.445Z"
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Axio",
                "squareFeet": 1045,
                "surveyDate": "2020-03-01",
                "occupancyRate": 93.6,
                "lastUpdatedDate": "2020-04-15T21:06:24.250",
                "numberUnitsBeds": 237,
                "propertyGoldenId": "PMST498969",
                "marketRentUnitBedAmount": 1685.76,
                "rentPerSquareFootAmount": 1.6,
                "effectiveRentUnitBedAmount": 1640.3,
                "marketStandardAdjustedRentUnitAmount": null,
                "indexedTimeStamp": "2020-10-03T10:06:37.263Z"
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Axio",
                "squareFeet": 1045,
                "surveyDate": "2020-04-01",
                "occupancyRate": 94.5,
                "lastUpdatedDate": "2020-05-15T20:00:44.810",
                "numberUnitsBeds": 237,
                "propertyGoldenId": "PMST498969",
                "marketRentUnitBedAmount": 1693.97,
                "rentPerSquareFootAmount": 1.6,
                "effectiveRentUnitBedAmount": 1641.2,
                "marketStandardAdjustedRentUnitAmount": null,
                "indexedTimeStamp": "2020-10-03T15:56:46.208Z"
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Axio",
                "squareFeet": 1045,
                "surveyDate": "2020-05-01",
                "occupancyRate": 94.5,
                "lastUpdatedDate": "2020-06-14T21:12:59.760",
                "numberUnitsBeds": 237,
                "propertyGoldenId": "PMST498969",
                "marketRentUnitBedAmount": 1681.76,
                "rentPerSquareFootAmount": 1.59,
                "effectiveRentUnitBedAmount": 1628.99,
                "marketStandardAdjustedRentUnitAmount": null,
                "indexedTimeStamp": "2020-10-03T22:36:50.775Z"
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Axio",
                "squareFeet": 1045,
                "surveyDate": "2020-06-01",
                "occupancyRate": 94,
                "lastUpdatedDate": "2020-07-17T19:15:13.310",
                "numberUnitsBeds": 237,
                "propertyGoldenId": "PMST498969",
                "marketRentUnitBedAmount": 1679.37,
                "rentPerSquareFootAmount": 1.59,
                "effectiveRentUnitBedAmount": 1627.38,
                "marketStandardAdjustedRentUnitAmount": null,
                "indexedTimeStamp": "2020-10-04T06:45:52.642Z"
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Axio",
                "squareFeet": 1045,
                "surveyDate": "2020-07-01",
                "occupancyRate": 94,
                "lastUpdatedDate": "2020-08-17T10:07:29.573",
                "numberUnitsBeds": 237,
                "propertyGoldenId": "PMST498969",
                "marketRentUnitBedAmount": 1679.37,
                "rentPerSquareFootAmount": 1.59,
                "effectiveRentUnitBedAmount": 1627.38,
                "marketStandardAdjustedRentUnitAmount": null,
                "indexedTimeStamp": "2020-10-04T11:59:09.561Z"
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Axio",
                "squareFeet": 1045,
                "surveyDate": "2020-08-01",
                "occupancyRate": 94.5,
                "lastUpdatedDate": "2020-09-24T10:28:06.950",
                "numberUnitsBeds": 237,
                "propertyGoldenId": "PMST498969",
                "marketRentUnitBedAmount": 1663.83,
                "rentPerSquareFootAmount": 1.57,
                "effectiveRentUnitBedAmount": 1609.26,
                "marketStandardAdjustedRentUnitAmount": null,
                "indexedTimeStamp": "2020-10-04T17:44:28.596Z"
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Axio",
                "squareFeet": 1045,
                "surveyDate": "2020-09-01",
                "occupancyRate": 94.5,
                "lastUpdatedDate": "2020-10-12T20:48:02.443",
                "numberUnitsBeds": 237,
                "propertyGoldenId": "PMST498969",
                "marketRentUnitBedAmount": 1662.33,
                "rentPerSquareFootAmount": 1.57,
                "effectiveRentUnitBedAmount": 1606,
                "marketStandardAdjustedRentUnitAmount": null,
                "indexedTimeStamp": "2020-10-13T19:38:37.844Z"
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Axio",
                "squareFeet": 1045,
                "surveyDate": "2020-10-01",
                "occupancyRate": 93.6,
                "lastUpdatedDate": "2020-11-28T10:54:34.740",
                "numberUnitsBeds": 237,
                "propertyGoldenId": "PMST498969",
                "marketRentUnitBedAmount": 1638.19,
                "rentPerSquareFootAmount": 1.55,
                "effectiveRentUnitBedAmount": 1588.16,
                "marketStandardAdjustedRentUnitAmount": null,
                "indexedTimeStamp": "2020-11-29T09:55:48.373Z"
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Yardi",
                "squareFeet": 905,
                "surveyDate": "2020-10-01",
                "occupancyRate": null,
                "lastUpdatedDate": "2020-12-16T21:22:46.637",
                "numberUnitsBeds": 262,
                "propertyGoldenId": "PMST498969",
                "marketRentUnitBedAmount": 1609.74,
                "rentPerSquareFootAmount": 1.68,
                "effectiveRentUnitBedAmount": 1503.21,
                "marketStandardAdjustedRentUnitAmount": 1530.73,
                "indexedTimeStamp": "2020-12-18T17:38:04.327Z"
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Yardi",
                "squareFeet": 905,
                "surveyDate": "2020-11-01",
                "occupancyRate": null,
                "lastUpdatedDate": "2020-12-16T21:22:46.637",
                "numberUnitsBeds": 262,
                "propertyGoldenId": "PMST498969",
                "marketRentUnitBedAmount": 1595.35,
                "rentPerSquareFootAmount": 1.67,
                "effectiveRentUnitBedAmount": 1488.82,
                "marketStandardAdjustedRentUnitAmount": 1516.33,
                "indexedTimeStamp": "2020-12-18T17:38:04.383Z"
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Axio",
                "squareFeet": 1045,
                "surveyDate": "2020-11-01",
                "occupancyRate": 93.6,
                "lastUpdatedDate": "2020-12-16T21:22:46.637",
                "numberUnitsBeds": 237,
                "propertyGoldenId": "PMST498969",
                "marketRentUnitBedAmount": 1638.19,
                "rentPerSquareFootAmount": 1.55,
                "effectiveRentUnitBedAmount": 1588.16,
                "marketStandardAdjustedRentUnitAmount": null,
                "indexedTimeStamp": "2020-12-18T17:38:03.614Z"
            }
        ]
    }
]