module.exports.data = [
    {
        "marketDashboardQueryRes": [
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Yardi",
                "squareFeet": null,
                "surveyDate": "2019-02-01",
                "occupancyRate": null,
                "lastUpdatedDate": "2019-04-05T15:56:06.513",
                "numberUnitsBeds": 78,
                "propertyGoldenId": "PMST492564",
                "marketRentUnitBedAmount": 1850.15,
                "rentPerSquareFootAmount": null,
                "effectiveRentUnitBedAmount": 1850.15,
                "marketStandardAdjustedRentUnitAmount": 1825.15,
                "indexedTimeStamp": "2020-10-01T12:30:35.317Z"
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Yardi",
                "squareFeet": null,
                "surveyDate": "2019-03-01",
                "occupancyRate": null,
                "lastUpdatedDate": "2019-04-05T15:56:06.513",
                "numberUnitsBeds": 78,
                "propertyGoldenId": "PMST492564",
                "marketRentUnitBedAmount": 1858.9,
                "rentPerSquareFootAmount": null,
                "effectiveRentUnitBedAmount": 1858.9,
                "marketStandardAdjustedRentUnitAmount": 1833.9,
                "indexedTimeStamp": "2020-10-01T12:30:35.323Z"
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Yardi",
                "squareFeet": null,
                "surveyDate": "2019-04-01",
                "occupancyRate": null,
                "lastUpdatedDate": "2019-05-03T16:25:21.460",
                "numberUnitsBeds": 78,
                "propertyGoldenId": "PMST492564",
                "marketRentUnitBedAmount": 1848.15,
                "rentPerSquareFootAmount": null,
                "effectiveRentUnitBedAmount": 1848.15,
                "marketStandardAdjustedRentUnitAmount": 1823.15,
                "indexedTimeStamp": "2020-10-01T15:45:29.128Z"
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Yardi",
                "squareFeet": null,
                "surveyDate": "2019-05-01",
                "occupancyRate": null,
                "lastUpdatedDate": "2019-06-07T16:08:35.083",
                "numberUnitsBeds": 78,
                "propertyGoldenId": "PMST492564",
                "marketRentUnitBedAmount": 1857.9,
                "rentPerSquareFootAmount": null,
                "effectiveRentUnitBedAmount": 1857.9,
                "marketStandardAdjustedRentUnitAmount": 1832.9,
                "indexedTimeStamp": "2020-10-01T19:18:38.417Z"
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Yardi",
                "squareFeet": null,
                "surveyDate": "2019-06-01",
                "occupancyRate": null,
                "lastUpdatedDate": "2019-08-03T20:55:44.743",
                "numberUnitsBeds": 78,
                "propertyGoldenId": "PMST492564",
                "marketRentUnitBedAmount": 1964.1,
                "rentPerSquareFootAmount": null,
                "effectiveRentUnitBedAmount": 1964.1,
                "marketStandardAdjustedRentUnitAmount": 1939.1,
                "indexedTimeStamp": "2020-10-02T00:37:14.731Z"
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Yardi",
                "squareFeet": null,
                "surveyDate": "2019-07-01",
                "occupancyRate": null,
                "lastUpdatedDate": "2019-08-03T20:55:44.743",
                "numberUnitsBeds": 78,
                "propertyGoldenId": "PMST492564",
                "marketRentUnitBedAmount": 1970.85,
                "rentPerSquareFootAmount": null,
                "effectiveRentUnitBedAmount": 1970.85,
                "marketStandardAdjustedRentUnitAmount": 1945.85,
                "indexedTimeStamp": "2020-10-02T00:37:14.737Z"
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Yardi",
                "squareFeet": null,
                "surveyDate": "2019-08-01",
                "occupancyRate": null,
                "lastUpdatedDate": "2019-09-03T21:09:59.237",
                "numberUnitsBeds": 78,
                "propertyGoldenId": "PMST492564",
                "marketRentUnitBedAmount": 1976.59,
                "rentPerSquareFootAmount": null,
                "effectiveRentUnitBedAmount": 1976.59,
                "marketStandardAdjustedRentUnitAmount": 1951.59,
                "indexedTimeStamp": "2020-10-02T04:59:09.191Z"
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Yardi",
                "squareFeet": null,
                "surveyDate": "2019-09-01",
                "occupancyRate": null,
                "lastUpdatedDate": "2019-11-19T12:07:19.390",
                "numberUnitsBeds": 78,
                "propertyGoldenId": "PMST492564",
                "marketRentUnitBedAmount": 1982.95,
                "rentPerSquareFootAmount": null,
                "effectiveRentUnitBedAmount": 1982.95,
                "marketStandardAdjustedRentUnitAmount": 1957.95,
                "indexedTimeStamp": "2020-10-02T11:13:56.703Z"
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Yardi",
                "squareFeet": null,
                "surveyDate": "2019-10-01",
                "occupancyRate": null,
                "lastUpdatedDate": "2019-11-19T12:10:46.227",
                "numberUnitsBeds": 78,
                "propertyGoldenId": "PMST492564",
                "marketRentUnitBedAmount": 1989.23,
                "rentPerSquareFootAmount": null,
                "effectiveRentUnitBedAmount": 1989.23,
                "marketStandardAdjustedRentUnitAmount": 1964.23,
                "indexedTimeStamp": "2020-10-02T13:37:46.922Z"
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Yardi",
                "squareFeet": null,
                "surveyDate": "2019-11-01",
                "occupancyRate": null,
                "lastUpdatedDate": "2020-01-04T10:12:44.607",
                "numberUnitsBeds": 78,
                "propertyGoldenId": "PMST492564",
                "marketRentUnitBedAmount": 1975.49,
                "rentPerSquareFootAmount": null,
                "effectiveRentUnitBedAmount": 1975.49,
                "marketStandardAdjustedRentUnitAmount": 1950.49,
                "indexedTimeStamp": "2020-10-02T16:42:42.578Z"
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Yardi",
                "squareFeet": null,
                "surveyDate": "2019-12-01",
                "occupancyRate": null,
                "lastUpdatedDate": "2020-02-04T19:44:27.720",
                "numberUnitsBeds": 78,
                "propertyGoldenId": "PMST492564",
                "marketRentUnitBedAmount": 1976.49,
                "rentPerSquareFootAmount": null,
                "effectiveRentUnitBedAmount": 1976.49,
                "marketStandardAdjustedRentUnitAmount": 1951.49,
                "indexedTimeStamp": "2020-10-02T20:46:54.202Z"
            },
            {
                "marketStandardAdjustedRentUnitAmount": 1959.23,
                "surveyDate": "2020-01-01",
                "effectiveRentUnitBedAmount": 1984.23,
                "rentPerSquareFootAmount": null,
                "propertyGoldenId": "PMST492564",
                "unitType": "Property Average",
                "marketRentUnitBedAmount": 1984.23,
                "lastUpdatedDate": "2020-03-04T14:49:25.650",
                "numberUnitsBeds": 78,
                "unitId": 0,
                "occupancyRate": null,
                "squareFeet": null,
                "dataSource": "Yardi",
                "indexedTimeStamp": "2020-10-03T02:23:04.882Z"
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Yardi",
                "squareFeet": null,
                "surveyDate": "2020-02-01",
                "occupancyRate": null,
                "lastUpdatedDate": "2020-04-04T07:07:53.220",
                "numberUnitsBeds": 78,
                "propertyGoldenId": "PMST492564",
                "marketRentUnitBedAmount": 2296.15,
                "rentPerSquareFootAmount": null,
                "effectiveRentUnitBedAmount": 2296.15,
                "marketStandardAdjustedRentUnitAmount": 2271.15,
                "indexedTimeStamp": "2020-10-03T07:56:59.766Z"
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Yardi",
                "squareFeet": null,
                "surveyDate": "2020-03-01",
                "occupancyRate": null,
                "lastUpdatedDate": "2020-05-05T12:03:34.683",
                "numberUnitsBeds": 78,
                "propertyGoldenId": "PMST492564",
                "marketRentUnitBedAmount": 2306.64,
                "rentPerSquareFootAmount": null,
                "effectiveRentUnitBedAmount": 2306.64,
                "marketStandardAdjustedRentUnitAmount": 2281.64,
                "indexedTimeStamp": "2020-10-03T12:00:36.041Z"
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Yardi",
                "squareFeet": null,
                "surveyDate": "2020-04-01",
                "occupancyRate": null,
                "lastUpdatedDate": "2020-05-05T12:06:30.553",
                "numberUnitsBeds": 78,
                "propertyGoldenId": "PMST492564",
                "marketRentUnitBedAmount": 2305.64,
                "rentPerSquareFootAmount": null,
                "effectiveRentUnitBedAmount": 2305.64,
                "marketStandardAdjustedRentUnitAmount": 2280.64,
                "indexedTimeStamp": "2020-10-03T14:40:56.921Z"
            },
            {
                "marketStandardAdjustedRentUnitAmount": 2323.08,
                "surveyDate": "2020-05-01",
                "effectiveRentUnitBedAmount": 2348.08,
                "rentPerSquareFootAmount": null,
                "propertyGoldenId": "PMST492564",
                "unitType": "Property Average",
                "marketRentUnitBedAmount": 2348.08,
                "lastUpdatedDate": "2020-07-14T11:14:39.030",
                "numberUnitsBeds": 78,
                "unitId": 0,
                "occupancyRate": null,
                "squareFeet": null,
                "dataSource": "Yardi",
                "indexedTimeStamp": "2020-10-04T03:32:40.472Z"
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Yardi",
                "squareFeet": null,
                "surveyDate": "2020-06-01",
                "occupancyRate": null,
                "lastUpdatedDate": "2020-07-14T11:17:25.660",
                "numberUnitsBeds": 78,
                "propertyGoldenId": "PMST492564",
                "marketRentUnitBedAmount": 2365.38,
                "rentPerSquareFootAmount": null,
                "effectiveRentUnitBedAmount": 2365.38,
                "marketStandardAdjustedRentUnitAmount": 2340.38,
                "indexedTimeStamp": "2020-10-04T03:38:56.379Z"
            },
            {
                "marketStandardAdjustedRentUnitAmount": 2350.87,
                "surveyDate": "2020-07-01",
                "effectiveRentUnitBedAmount": 2375.87,
                "rentPerSquareFootAmount": null,
                "propertyGoldenId": "PMST492564",
                "unitType": "Property Average",
                "marketRentUnitBedAmount": 2375.87,
                "lastUpdatedDate": "2020-09-04T12:19:30.033",
                "numberUnitsBeds": 78,
                "unitId": 0,
                "occupancyRate": null,
                "squareFeet": null,
                "dataSource": "Yardi",
                "indexedTimeStamp": "2020-10-04T14:49:24.583Z"
            },
            {
                "marketStandardAdjustedRentUnitAmount": 2343.38,
                "surveyDate": "2020-08-01",
                "effectiveRentUnitBedAmount": 2368.38,
                "rentPerSquareFootAmount": null,
                "propertyGoldenId": "PMST492564",
                "unitType": "Property Average",
                "marketRentUnitBedAmount": 2368.38,
                "lastUpdatedDate": "2020-10-03T18:23:48.123",
                "numberUnitsBeds": 78,
                "unitId": 0,
                "occupancyRate": null,
                "squareFeet": null,
                "dataSource": "Yardi",
                "indexedTimeStamp": "2020-10-04T21:03:04.804Z"
            },
            {
                "marketStandardAdjustedRentUnitAmount": 2359.36,
                "surveyDate": "2020-09-01",
                "effectiveRentUnitBedAmount": 2384.36,
                "rentPerSquareFootAmount": null,
                "propertyGoldenId": "PMST492564",
                "unitType": "Property Average",
                "marketRentUnitBedAmount": 2384.36,
                "lastUpdatedDate": "2020-11-03T17:28:09.183",
                "numberUnitsBeds": 78,
                "unitId": 0,
                "occupancyRate": null,
                "squareFeet": null,
                "dataSource": "Yardi",
                "indexedTimeStamp": "2020-11-19T09:25:41.443Z"
            }
        ]
    }, {
        "marketDashboardQueryRes": [
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Yardi",
                "squareFeet": 1110,
                "surveyDate": "2018-02-01",
                "occupancyRate": null,
                "lastUpdatedDate": "2018-04-03T10:05:32.680",
                "numberUnitsBeds": 335,
                "propertyGoldenId": "PMST121546",
                "marketRentUnitBedAmount": 2309.51,
                "rentPerSquareFootAmount": 2.15,
                "effectiveRentUnitBedAmount": 2309.51,
                "marketStandardAdjustedRentUnitAmount": 2293.93
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Yardi",
                "squareFeet": 1110,
                "surveyDate": "2018-03-01",
                "occupancyRate": null,
                "lastUpdatedDate": "2018-05-03T11:08:14.470",
                "numberUnitsBeds": 335,
                "propertyGoldenId": "PMST121546",
                "marketRentUnitBedAmount": 2318.4,
                "rentPerSquareFootAmount": 2.16,
                "effectiveRentUnitBedAmount": 2318.4,
                "marketStandardAdjustedRentUnitAmount": 2302.82
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Yardi",
                "squareFeet": 1110,
                "surveyDate": "2018-04-01",
                "occupancyRate": null,
                "lastUpdatedDate": "2018-06-05T11:45:06.750",
                "numberUnitsBeds": 335,
                "propertyGoldenId": "PMST121546",
                "marketRentUnitBedAmount": 2321.93,
                "rentPerSquareFootAmount": 2.16,
                "effectiveRentUnitBedAmount": 2321.93,
                "marketStandardAdjustedRentUnitAmount": 2306.35
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Yardi",
                "squareFeet": 1110,
                "surveyDate": "2018-05-01",
                "occupancyRate": null,
                "lastUpdatedDate": "2018-06-05T11:45:06.750",
                "numberUnitsBeds": 335,
                "propertyGoldenId": "PMST121546",
                "marketRentUnitBedAmount": 2350.6,
                "rentPerSquareFootAmount": 2.19,
                "effectiveRentUnitBedAmount": 2350.6,
                "marketStandardAdjustedRentUnitAmount": 2335.02
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Yardi",
                "squareFeet": 1110,
                "surveyDate": "2018-06-01",
                "occupancyRate": null,
                "lastUpdatedDate": "2018-08-04T16:56:55.950",
                "numberUnitsBeds": 335,
                "propertyGoldenId": "PMST121546",
                "marketRentUnitBedAmount": 2304.52,
                "rentPerSquareFootAmount": 2.17,
                "effectiveRentUnitBedAmount": 2304.52,
                "marketStandardAdjustedRentUnitAmount": 2288.94
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Yardi",
                "squareFeet": 1110,
                "surveyDate": "2018-07-01",
                "occupancyRate": null,
                "lastUpdatedDate": "2018-08-04T16:56:55.950",
                "numberUnitsBeds": 335,
                "propertyGoldenId": "PMST121546",
                "marketRentUnitBedAmount": 2312.48,
                "rentPerSquareFootAmount": 2.18,
                "effectiveRentUnitBedAmount": 2312.48,
                "marketStandardAdjustedRentUnitAmount": 2296.9
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Yardi",
                "squareFeet": 1110,
                "surveyDate": "2018-08-01",
                "occupancyRate": null,
                "lastUpdatedDate": "2018-09-06T10:29:25.843",
                "numberUnitsBeds": 335,
                "propertyGoldenId": "PMST121546",
                "marketRentUnitBedAmount": 2312.48,
                "rentPerSquareFootAmount": 2.18,
                "effectiveRentUnitBedAmount": 2312.48,
                "marketStandardAdjustedRentUnitAmount": 2296.9
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Yardi",
                "squareFeet": 1110,
                "surveyDate": "2018-09-01",
                "occupancyRate": null,
                "lastUpdatedDate": "2018-10-03T16:35:59.967",
                "numberUnitsBeds": 335,
                "propertyGoldenId": "PMST121546",
                "marketRentUnitBedAmount": 2309.02,
                "rentPerSquareFootAmount": 2.17,
                "effectiveRentUnitBedAmount": 2309.02,
                "marketStandardAdjustedRentUnitAmount": 2293.44
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Yardi",
                "squareFeet": 1110,
                "surveyDate": "2018-10-01",
                "occupancyRate": null,
                "lastUpdatedDate": "2018-12-04T13:36:52.073",
                "numberUnitsBeds": 335,
                "propertyGoldenId": "PMST121546",
                "marketRentUnitBedAmount": 2242.56,
                "rentPerSquareFootAmount": 2.08,
                "effectiveRentUnitBedAmount": 2242.56,
                "marketStandardAdjustedRentUnitAmount": 2226.98
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Yardi",
                "squareFeet": 1110,
                "surveyDate": "2018-11-01",
                "occupancyRate": null,
                "lastUpdatedDate": "2018-12-04T13:36:52.073",
                "numberUnitsBeds": 335,
                "propertyGoldenId": "PMST121546",
                "marketRentUnitBedAmount": 2239.85,
                "rentPerSquareFootAmount": 2.07,
                "effectiveRentUnitBedAmount": 2239.85,
                "marketStandardAdjustedRentUnitAmount": 2224.27
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Yardi",
                "squareFeet": 1110,
                "surveyDate": "2018-12-01",
                "occupancyRate": null,
                "lastUpdatedDate": "2019-01-08T15:55:14.650",
                "numberUnitsBeds": 335,
                "propertyGoldenId": "PMST121546",
                "marketRentUnitBedAmount": 2231.4,
                "rentPerSquareFootAmount": 2.07,
                "effectiveRentUnitBedAmount": 2231.4,
                "marketStandardAdjustedRentUnitAmount": 2215.82
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Yardi",
                "squareFeet": 1110,
                "surveyDate": "2019-01-01",
                "occupancyRate": null,
                "lastUpdatedDate": "2019-02-06T19:03:20.600",
                "numberUnitsBeds": 335,
                "propertyGoldenId": "PMST121546",
                "marketRentUnitBedAmount": 2225.78,
                "rentPerSquareFootAmount": 2.06,
                "effectiveRentUnitBedAmount": 2225.78,
                "marketStandardAdjustedRentUnitAmount": 2210.2
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Yardi",
                "squareFeet": 1110,
                "surveyDate": "2019-02-01",
                "occupancyRate": null,
                "lastUpdatedDate": "2019-04-05T15:56:06.513",
                "numberUnitsBeds": 335,
                "propertyGoldenId": "PMST121546",
                "marketRentUnitBedAmount": 2273.21,
                "rentPerSquareFootAmount": 2.1,
                "effectiveRentUnitBedAmount": 2273.21,
                "marketStandardAdjustedRentUnitAmount": 2257.63,
                "indexedTimeStamp": "2020-10-01T11:25:40.423Z"
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Yardi",
                "squareFeet": 1110,
                "surveyDate": "2019-03-01",
                "occupancyRate": null,
                "lastUpdatedDate": "2019-04-05T15:56:06.513",
                "numberUnitsBeds": 335,
                "propertyGoldenId": "PMST121546",
                "marketRentUnitBedAmount": 2301.8,
                "rentPerSquareFootAmount": 2.12,
                "effectiveRentUnitBedAmount": 2301.8,
                "marketStandardAdjustedRentUnitAmount": 2286.22,
                "indexedTimeStamp": "2020-10-01T11:25:40.432Z"
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Yardi",
                "squareFeet": 1110,
                "surveyDate": "2019-04-01",
                "occupancyRate": null,
                "lastUpdatedDate": "2019-05-03T16:25:21.460",
                "numberUnitsBeds": 335,
                "propertyGoldenId": "PMST121546",
                "marketRentUnitBedAmount": 2301.8,
                "rentPerSquareFootAmount": 2.12,
                "effectiveRentUnitBedAmount": 2301.8,
                "marketStandardAdjustedRentUnitAmount": 2286.22,
                "indexedTimeStamp": "2020-10-01T15:40:28.278Z"
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Yardi",
                "squareFeet": 1110,
                "surveyDate": "2019-05-01",
                "occupancyRate": null,
                "lastUpdatedDate": "2019-06-07T16:08:35.083",
                "numberUnitsBeds": 335,
                "propertyGoldenId": "PMST121546",
                "marketRentUnitBedAmount": 2308.82,
                "rentPerSquareFootAmount": 2.13,
                "effectiveRentUnitBedAmount": 2308.82,
                "marketStandardAdjustedRentUnitAmount": 2293.24,
                "indexedTimeStamp": "2020-10-01T18:36:46.990Z"
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Yardi",
                "squareFeet": 1110,
                "surveyDate": "2019-06-01",
                "occupancyRate": null,
                "lastUpdatedDate": "2019-08-03T20:55:44.743",
                "numberUnitsBeds": 335,
                "propertyGoldenId": "PMST121546",
                "marketRentUnitBedAmount": 2193.81,
                "rentPerSquareFootAmount": 2.03,
                "effectiveRentUnitBedAmount": 2193.81,
                "marketStandardAdjustedRentUnitAmount": 2191.46,
                "indexedTimeStamp": "2020-10-02T00:42:54.626Z"
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Yardi",
                "squareFeet": 1110,
                "surveyDate": "2019-07-01",
                "occupancyRate": null,
                "lastUpdatedDate": "2019-08-03T20:55:44.743",
                "numberUnitsBeds": 335,
                "propertyGoldenId": "PMST121546",
                "marketRentUnitBedAmount": 2193.81,
                "rentPerSquareFootAmount": 2.03,
                "effectiveRentUnitBedAmount": 2193.81,
                "marketStandardAdjustedRentUnitAmount": 2191.46,
                "indexedTimeStamp": "2020-10-02T00:42:54.633Z"
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Yardi",
                "squareFeet": 1110,
                "surveyDate": "2019-08-01",
                "occupancyRate": null,
                "lastUpdatedDate": "2019-09-03T21:09:59.237",
                "numberUnitsBeds": 335,
                "propertyGoldenId": "PMST121546",
                "marketRentUnitBedAmount": 2198.29,
                "rentPerSquareFootAmount": 2.04,
                "effectiveRentUnitBedAmount": 2198.29,
                "marketStandardAdjustedRentUnitAmount": 2195.94,
                "indexedTimeStamp": "2020-10-02T05:50:25.373Z"
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Yardi",
                "squareFeet": 1110,
                "surveyDate": "2019-09-01",
                "occupancyRate": null,
                "lastUpdatedDate": "2019-11-19T12:07:19.390",
                "numberUnitsBeds": 335,
                "propertyGoldenId": "PMST121546",
                "marketRentUnitBedAmount": 2233.51,
                "rentPerSquareFootAmount": 2.08,
                "effectiveRentUnitBedAmount": 2233.51,
                "marketStandardAdjustedRentUnitAmount": 2231.16,
                "indexedTimeStamp": "2020-10-02T12:13:33.437Z"
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Yardi",
                "squareFeet": 1110,
                "surveyDate": "2019-10-01",
                "occupancyRate": null,
                "lastUpdatedDate": "2019-11-19T12:10:46.227",
                "numberUnitsBeds": 335,
                "propertyGoldenId": "PMST121546",
                "marketRentUnitBedAmount": 2247.33,
                "rentPerSquareFootAmount": 2.1,
                "effectiveRentUnitBedAmount": 2247.33,
                "marketStandardAdjustedRentUnitAmount": 2231.75,
                "indexedTimeStamp": "2020-10-02T13:00:19.799Z"
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Yardi",
                "squareFeet": 1110,
                "surveyDate": "2019-11-01",
                "occupancyRate": null,
                "lastUpdatedDate": "2020-01-04T10:12:44.607",
                "numberUnitsBeds": 335,
                "propertyGoldenId": "PMST121546",
                "marketRentUnitBedAmount": 2231.73,
                "rentPerSquareFootAmount": 2.08,
                "effectiveRentUnitBedAmount": 2231.73,
                "marketStandardAdjustedRentUnitAmount": 2216.15,
                "indexedTimeStamp": "2020-10-02T17:23:19.698Z"
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Yardi",
                "squareFeet": 1110,
                "surveyDate": "2019-12-01",
                "occupancyRate": null,
                "lastUpdatedDate": "2020-02-04T19:44:27.720",
                "numberUnitsBeds": 335,
                "propertyGoldenId": "PMST121546",
                "marketRentUnitBedAmount": 2238.18,
                "rentPerSquareFootAmount": 2.09,
                "effectiveRentUnitBedAmount": 2238.18,
                "marketStandardAdjustedRentUnitAmount": 2222.6,
                "indexedTimeStamp": "2020-10-02T20:08:23.533Z"
            },
            {
                "marketStandardAdjustedRentUnitAmount": 2223,
                "surveyDate": "2020-01-01",
                "effectiveRentUnitBedAmount": 2238.58,
                "rentPerSquareFootAmount": 2.09,
                "propertyGoldenId": "PMST121546",
                "unitType": "Property Average",
                "marketRentUnitBedAmount": 2238.58,
                "lastUpdatedDate": "2020-03-04T14:49:25.650",
                "numberUnitsBeds": 335,
                "unitId": 0,
                "occupancyRate": null,
                "squareFeet": 1110,
                "dataSource": "Yardi",
                "indexedTimeStamp": "2020-10-03T02:21:00.141Z"
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Yardi",
                "squareFeet": 1110,
                "surveyDate": "2020-02-01",
                "occupancyRate": null,
                "lastUpdatedDate": "2020-04-04T07:07:53.220",
                "numberUnitsBeds": 335,
                "propertyGoldenId": "PMST121546",
                "marketRentUnitBedAmount": 2200.18,
                "rentPerSquareFootAmount": 2.03,
                "effectiveRentUnitBedAmount": 2200.18,
                "marketStandardAdjustedRentUnitAmount": 2184.6,
                "indexedTimeStamp": "2020-10-03T08:19:43.149Z"
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Yardi",
                "squareFeet": 1110,
                "surveyDate": "2020-03-01",
                "occupancyRate": null,
                "lastUpdatedDate": "2020-05-05T12:03:34.683",
                "numberUnitsBeds": 335,
                "propertyGoldenId": "PMST121546",
                "marketRentUnitBedAmount": 2209.91,
                "rentPerSquareFootAmount": 2.04,
                "effectiveRentUnitBedAmount": 2209.91,
                "marketStandardAdjustedRentUnitAmount": 2194.33,
                "indexedTimeStamp": "2020-10-03T11:57:22.761Z"
            },
            {
                "marketStandardAdjustedRentUnitAmount": 2190.31,
                "surveyDate": "2020-04-01",
                "effectiveRentUnitBedAmount": 2205.89,
                "rentPerSquareFootAmount": 2.04,
                "propertyGoldenId": "PMST121546",
                "unitType": "Property Average",
                "marketRentUnitBedAmount": 2205.89,
                "lastUpdatedDate": "2020-06-04T11:12:15.690",
                "numberUnitsBeds": 335,
                "unitId": 0,
                "occupancyRate": null,
                "squareFeet": 1110,
                "dataSource": "Yardi",
                "indexedTimeStamp": "2020-10-03T18:55:08.994Z"
            },
            {
                "marketStandardAdjustedRentUnitAmount": 2120.26,
                "surveyDate": "2020-05-01",
                "effectiveRentUnitBedAmount": 2135.84,
                "rentPerSquareFootAmount": 1.97,
                "propertyGoldenId": "PMST121546",
                "unitType": "Property Average",
                "marketRentUnitBedAmount": 2135.84,
                "lastUpdatedDate": "2020-07-14T11:14:39.030",
                "numberUnitsBeds": 335,
                "unitId": 0,
                "occupancyRate": null,
                "squareFeet": 1110,
                "dataSource": "Yardi",
                "indexedTimeStamp": "2020-10-04T01:53:16.138Z"
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Yardi",
                "squareFeet": 1110,
                "surveyDate": "2020-06-01",
                "occupancyRate": null,
                "lastUpdatedDate": "2020-07-14T11:17:25.660",
                "numberUnitsBeds": 335,
                "propertyGoldenId": "PMST121546",
                "marketRentUnitBedAmount": 2113.35,
                "rentPerSquareFootAmount": 1.96,
                "effectiveRentUnitBedAmount": 2113.35,
                "marketStandardAdjustedRentUnitAmount": 2097.77,
                "indexedTimeStamp": "2020-10-04T05:10:37.847Z"
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Yardi",
                "squareFeet": 1110,
                "surveyDate": "2020-07-01",
                "occupancyRate": null,
                "lastUpdatedDate": "2020-08-04T12:02:57.103",
                "numberUnitsBeds": 335,
                "propertyGoldenId": "PMST121546",
                "marketRentUnitBedAmount": 2255.34,
                "rentPerSquareFootAmount": 2.13,
                "effectiveRentUnitBedAmount": 2255.34,
                "marketStandardAdjustedRentUnitAmount": 2239.76,
                "indexedTimeStamp": "2020-10-04T09:51:25.471Z"
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Yardi",
                "squareFeet": 1110,
                "surveyDate": "2020-08-01",
                "occupancyRate": null,
                "lastUpdatedDate": "2020-09-04T12:22:54.547",
                "numberUnitsBeds": 335,
                "propertyGoldenId": "PMST121546",
                "marketRentUnitBedAmount": 2206.59,
                "rentPerSquareFootAmount": 2.09,
                "effectiveRentUnitBedAmount": 2206.59,
                "marketStandardAdjustedRentUnitAmount": 2191.01,
                "indexedTimeStamp": "2020-10-04T16:21:19.985Z"
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Yardi",
                "squareFeet": 1110,
                "surveyDate": "2020-09-01",
                "occupancyRate": null,
                "lastUpdatedDate": "2020-10-03T18:26:16.347",
                "numberUnitsBeds": 335,
                "propertyGoldenId": "PMST121546",
                "marketRentUnitBedAmount": 2294.04,
                "rentPerSquareFootAmount": 2.16,
                "effectiveRentUnitBedAmount": 2294.04,
                "marketStandardAdjustedRentUnitAmount": 2278.47,
                "indexedTimeStamp": "2020-10-04T21:42:58.399Z"
            }
        ]
    }, {
        marketDashboardQueryRes: [
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Yardi",
                "squareFeet": null,
                "surveyDate": "2019-02-01",
                "occupancyRate": null,
                "lastUpdatedDate": "2019-04-05T15:56:06.513",
                "numberUnitsBeds": 78,
                "propertyGoldenId": "PMST492564",
                "marketRentUnitBedAmount": 1850.15,
                "rentPerSquareFootAmount": null,
                "effectiveRentUnitBedAmount": 1850.15,
                "marketStandardAdjustedRentUnitAmount": 1825.15,
                "indexedTimeStamp": "2020-10-01T12:30:35.317Z"
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Axio",
                "squareFeet": null,
                "surveyDate": "2019-02-01",
                "occupancyRate": null,
                "lastUpdatedDate": "2019-04-05T15:56:06.513",
                "numberUnitsBeds": 78,
                "propertyGoldenId": "PMST492564",
                "marketRentUnitBedAmount": 1850.15,
                "rentPerSquareFootAmount": null,
                "effectiveRentUnitBedAmount": 1850.15,
                "marketStandardAdjustedRentUnitAmount": 1825.15,
                "indexedTimeStamp": "2020-10-01T12:30:35.317Z"
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Axio",
                "squareFeet": null,
                "surveyDate": "2019-03-01",
                "occupancyRate": null,
                "lastUpdatedDate": "2019-04-05T15:56:06.513",
                "numberUnitsBeds": 78,
                "propertyGoldenId": "PMST492564",
                "marketRentUnitBedAmount": 1850.15,
                "rentPerSquareFootAmount": null,
                "effectiveRentUnitBedAmount": 1850.15,
                "marketStandardAdjustedRentUnitAmount": 1825.15,
                "indexedTimeStamp": "2020-10-01T12:30:35.317Z"
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Yardi",
                "squareFeet": null,
                "surveyDate": "2019-03-01",
                "occupancyRate": null,
                "lastUpdatedDate": "2019-04-05T15:56:06.513",
                "numberUnitsBeds": 78,
                "propertyGoldenId": "PMST492564",
                "marketRentUnitBedAmount": 1850.15,
                "rentPerSquareFootAmount": null,
                "effectiveRentUnitBedAmount": 1850.15,
                "marketStandardAdjustedRentUnitAmount": 1825.15,
                "indexedTimeStamp": "2020-10-01T12:30:35.317Z"
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Axio",
                "squareFeet": null,
                "surveyDate": "2020-03-01",
                "occupancyRate": null,
                "lastUpdatedDate": "2019-04-05T15:56:06.513",
                "numberUnitsBeds": 78,
                "propertyGoldenId": "PMST492564",
                "marketRentUnitBedAmount": 1850.15,
                "rentPerSquareFootAmount": null,
                "effectiveRentUnitBedAmount": null,
                "marketStandardAdjustedRentUnitAmount": 1825.15,
                "indexedTimeStamp": "2020-10-01T12:30:35.317Z"
            }
            ,
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Yardi",
                "squareFeet": null,
                "surveyDate": "2020-03-01",
                "occupancyRate": null,
                "lastUpdatedDate": "2019-04-05T15:56:06.513",
                "numberUnitsBeds": 78,
                "propertyGoldenId": "PMST492564",
                "marketRentUnitBedAmount": 1850.15,
                "rentPerSquareFootAmount": null,
                "effectiveRentUnitBedAmount": null,
                "marketStandardAdjustedRentUnitAmount": 1825.15,
                "indexedTimeStamp": "2020-10-01T12:30:35.317Z"
            }
        ]
    }, {
        marketDashboardQueryRes: [
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Yardi",
                "squareFeet": null,
                "surveyDate": "2019-02-01",
                "occupancyRate": 100,
                "lastUpdatedDate": "2019-04-05T15:56:06.513",
                "numberUnitsBeds": 78,
                "propertyGoldenId": "PMST492564",
                "marketRentUnitBedAmount": 1850.15,
                "rentPerSquareFootAmount": 100,
                "effectiveRentUnitBedAmount": 111,
                "marketStandardAdjustedRentUnitAmount": 1825.15,
                "indexedTimeStamp": "2020-10-01T12:30:35.317Z"
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Yardi",
                "squareFeet": null,
                "surveyDate": "2019-03-01",
                "occupancyRate": 100,
                "lastUpdatedDate": "2019-04-05T15:56:06.513",
                "numberUnitsBeds": 78,
                "propertyGoldenId": "PMST492564",
                "marketRentUnitBedAmount": 1850.15,
                "rentPerSquareFootAmount": 100,
                "effectiveRentUnitBedAmount": 222,
                "marketStandardAdjustedRentUnitAmount": 1825.15,
                "indexedTimeStamp": "2020-10-01T12:30:35.317Z"
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Axio",
                "squareFeet": null,
                "surveyDate": "2019-02-01",
                "occupancyRate": 100,
                "lastUpdatedDate": "2019-04-05T15:56:06.513",
                "numberUnitsBeds": 78,
                "propertyGoldenId": "PMST492564",
                "marketRentUnitBedAmount": 1850.15,
                "rentPerSquareFootAmount": 100,
                "effectiveRentUnitBedAmount": 333,
                "marketStandardAdjustedRentUnitAmount": 1825.15,
                "indexedTimeStamp": "2020-10-01T12:30:35.317Z"
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Axio",
                "squareFeet": null,
                "surveyDate": "2020-02-01",
                "occupancyRate": 100,
                "lastUpdatedDate": "2019-04-05T15:56:06.513",
                "numberUnitsBeds": 78,
                "propertyGoldenId": "PMST492564",
                "marketRentUnitBedAmount": 1850.15,
                "rentPerSquareFootAmount": 100,
                "effectiveRentUnitBedAmount": 1111,
                "marketStandardAdjustedRentUnitAmount": 1825.15,
                "indexedTimeStamp": "2020-10-01T12:30:35.317Z"
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Yardi",
                "squareFeet": null,
                "surveyDate": "2020-02-01",
                "occupancyRate": 100,
                "lastUpdatedDate": "2019-04-05T15:56:06.513",
                "numberUnitsBeds": 78,
                "propertyGoldenId": "PMST492564",
                "marketRentUnitBedAmount": 1850.15,
                "rentPerSquareFootAmount": 100,
                "effectiveRentUnitBedAmount": 1111,
                "marketStandardAdjustedRentUnitAmount": 1825.15,
                "indexedTimeStamp": "2020-10-01T12:30:35.317Z"
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Yardi",
                "squareFeet": null,
                "surveyDate": "2020-03-01",
                "occupancyRate": 100,
                "lastUpdatedDate": "2019-04-05T15:56:06.513",
                "numberUnitsBeds": 78,
                "propertyGoldenId": "PMST492564",
                "marketRentUnitBedAmount": 1850.15,
                "rentPerSquareFootAmount": 100,
                "effectiveRentUnitBedAmount": 2222,
                "marketStandardAdjustedRentUnitAmount": 1825.15,
                "indexedTimeStamp": "2020-10-01T12:30:35.317Z"
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Axio",
                "squareFeet": null,
                "surveyDate": "2020-03-01",
                "occupancyRate": 100,
                "lastUpdatedDate": "2019-04-05T15:56:06.513",
                "numberUnitsBeds": 78,
                "propertyGoldenId": "PMST492564",
                "marketRentUnitBedAmount": 1850.15,
                "rentPerSquareFootAmount": 100,
                "effectiveRentUnitBedAmount": 3333,
                "marketStandardAdjustedRentUnitAmount": 1825.15,
                "indexedTimeStamp": "2020-10-01T12:30:35.317Z"
            },
        ]
    }, {
        marketDashboardQueryRes: [
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Yardi",
                "squareFeet": null,
                "surveyDate": "2019-02-01",
                "occupancyRate": 100,
                "lastUpdatedDate": "2019-04-05T15:56:06.513",
                "numberUnitsBeds": 78,
                "propertyGoldenId": "PMST492564",
                "marketRentUnitBedAmount": 1850.15,
                "rentPerSquareFootAmount": 100,
                "effectiveRentUnitBedAmount": 111,
                "marketStandardAdjustedRentUnitAmount": 1825.15,
                "indexedTimeStamp": "2020-10-01T12:30:35.317Z"
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Axio",
                "squareFeet": null,
                "surveyDate": "2019-02-01",
                "occupancyRate": 100,
                "lastUpdatedDate": "2019-04-05T15:56:06.513",
                "numberUnitsBeds": 78,
                "propertyGoldenId": "PMST492564",
                "marketRentUnitBedAmount": 1850.15,
                "rentPerSquareFootAmount": 100,
                "effectiveRentUnitBedAmount": 111,
                "marketStandardAdjustedRentUnitAmount": 1825.15,
                "indexedTimeStamp": "2020-10-01T12:30:35.317Z"
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Axio",
                "squareFeet": null,
                "surveyDate": "2020-02-01",
                "occupancyRate": 100,
                "lastUpdatedDate": "2019-04-05T15:56:06.513",
                "numberUnitsBeds": 78,
                "propertyGoldenId": "PMST492564",
                "marketRentUnitBedAmount": 1850.15,
                "rentPerSquareFootAmount": 100,
                "effectiveRentUnitBedAmount": 111,
                "marketStandardAdjustedRentUnitAmount": 1825.15,
                "indexedTimeStamp": "2020-10-01T12:30:35.317Z"
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Yardi",
                "squareFeet": null,
                "surveyDate": "2020-02-01",
                "occupancyRate": 100,
                "lastUpdatedDate": "2019-04-05T15:56:06.513",
                "numberUnitsBeds": 78,
                "propertyGoldenId": "PMST492564",
                "marketRentUnitBedAmount": 1850.15,
                "rentPerSquareFootAmount": 100,
                "effectiveRentUnitBedAmount": 111,
                "marketStandardAdjustedRentUnitAmount": 1825.15,
                "indexedTimeStamp": "2020-10-01T12:30:35.317Z"
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Yardi",
                "squareFeet": null,
                "surveyDate": "2020-02-01",
                "occupancyRate": 100,
                "lastUpdatedDate": "2019-04-05T15:56:06.513",
                "numberUnitsBeds": 78,
                "propertyGoldenId": "PMST492564",
                "marketRentUnitBedAmount": 10000000,
                "rentPerSquareFootAmount": 100,
                "effectiveRentUnitBedAmount": 10000000,
                "marketStandardAdjustedRentUnitAmount": 1825.15,
                "indexedTimeStamp": "2020-10-01T12:30:35.317Z"
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Yardi",
                "squareFeet": null,
                "surveyDate": "2019-03-01",
                "occupancyRate": 100,
                "lastUpdatedDate": "2019-04-05T15:56:06.513",
                "numberUnitsBeds": 78,
                "propertyGoldenId": "PMST492564",
                "marketRentUnitBedAmount": 10000000,
                "rentPerSquareFootAmount": 100,
                "effectiveRentUnitBedAmount": 10000000,
                "marketStandardAdjustedRentUnitAmount": 1825.15,
                "indexedTimeStamp": "2020-10-01T12:30:35.317Z"
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Axio",
                "squareFeet": null,
                "surveyDate": "2020-03-01",
                "occupancyRate": 100,
                "lastUpdatedDate": "2019-04-05T15:56:06.513",
                "numberUnitsBeds": 78,
                "propertyGoldenId": "PMST492564",
                "marketRentUnitBedAmount": 10000000,
                "rentPerSquareFootAmount": 100,
                "effectiveRentUnitBedAmount": 10000000,
                "marketStandardAdjustedRentUnitAmount": 1825.15,
                "indexedTimeStamp": "2020-10-01T12:30:35.317Z"
            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Yardi",
                "squareFeet": null,
                "surveyDate": "2020-03-01",
                "occupancyRate": 100,
                "lastUpdatedDate": "2019-04-05T15:56:06.513",
                "numberUnitsBeds": 78,
                "propertyGoldenId": "PMST492564",
                "marketRentUnitBedAmount": 10000000,
                "rentPerSquareFootAmount": 100,
                "effectiveRentUnitBedAmount": 10000000,
                "marketStandardAdjustedRentUnitAmount": 1825.15,
                "indexedTimeStamp": "2020-10-01T12:30:35.317Z"

            },
            {
                "unitId": 0,
                "unitType": "Property Average",
                "dataSource": "Yardi",
                "squareFeet": null,
                "surveyDate": "2020-03-01",
                "occupancyRate": 100,
                "lastUpdatedDate": "2019-04-05T15:56:06.513",
                "numberUnitsBeds": 78,
                "propertyGoldenId": "PMST492564",
                "marketRentUnitBedAmount": 10000000,
                "rentPerSquareFootAmount": 100,
                "effectiveRentUnitBedAmount": 555,
                "marketStandardAdjustedRentUnitAmount": 1825.15,
                "indexedTimeStamp": "2020-10-01T12:30:35.317Z"
            }
        ]
    }
]